#!/bin/bash
# $1 is the temp file containing the commit message
issue_number=`cat $1 | xargs | sed 's/*#\([0-9]*\).*/\1/'`
echo "issuenumber: $issue_number"
repo="`git remote show origin | grep "Push" | xargs | sed 's/.*:\(.*\)/\1/')`"
curl -s https://api.github.com/repos/$repo/issues/$issue_number | grep -q "\"Not Found\"" > /dev/null
exit $((1 -$?))

